### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jeybee74** [martinville/solarsynkv2#14]
Some inverter integrations has the ability to communicate directly with the inverter via the wifi-dongle.
like this one: https://github.com/torsteinelv/tte-home-assistant-addons/tree/main/pysolarmanv5-proxy
(doesn't work with the magpie dongle included with my SS 12kW 3p)

This eliminates the the need for internet communication and is not dependent on the (sunsynk) cloud service to be online to fetch data or change parameters on the inverter.

Is this something that could be integrated in this amazing Sunsynk integration?

BR Jon, Norway

**Comment by martinville** [comment]
Hi there.

Unfortunately the only way to my knowledge to access data points from your inverter is to either gather them via the SS portal or to make a use of custom or modified hardware attached to the inverter serial or Mod/Can bus serial ports and cannot be done on its own  from a HA addon without intervening on a hardware level.

The SS Dongle does not expose any information that you can connect to unfortunately. That would have been great if it did. I also think its not in the interest Dye/Sunsynk to make that available as it would take away "control" from their business. I don't have any hopes that it will become available in the future.

Also the SS dongle is hard coded to send data to a specific domain name via a hard coded DNS (Google DNS) which makes it harder to intercept. You can however intercept the data by means of a transparent proxy because the gateway on the dongle setup screen is configurable. But then you are dealing both text based proxying as well as DNS routes on a packet level.
(bit out of my league)

Therefore I will not be attempting to add such functionality. 
If anything I would most probably start a totally new project for that and making use of a proper coding language as opposed to a simple bash script (SolarSynk is just a bash script)


Sorry  about that ;-)
